up:
	docker-compose up -d

down:
	docker-compose down

build:
	docker-compose build

test:
	docker-compose run web npm test

eject:
	docker-compose run web npm run eject

dev: # build in local for dev
	npm run build

local: # auto-build in local for dev
	npm start