version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      # localのnode_modulesの変更をコンテナに反映されないように、空のnode_modulesをマウント
      - /app/node_modules
    command: npm run dev