version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    #   # volume mount先を変えることで、directory上にnode_modulesが現れないようにする
    #   # volume mountできると同時に、docker volumeを削除したら、node_modulesも消えてくれる
      - node_modules:/app/node_modules
    command: node server.js
    # tty: true
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      # cacheで少しでも高速化するため、buildkitを有効にする。もしかしたら不要？
      - DOCKER_BUILDKIT=1
    volumes:
      - ./client:/app
      # localのnode_modulesの変更をコンテナに反映されないように、名前付きnode_modulesをマウント
      - client_node_modules:/app/node_modules

    command: npm start

# 全てのコンテナが共有する
volumes:
  # 他のprojectでも、node_modulesという名前のvolumeを指定したら、それが使われる
  node_modules:
  client_node_modules: